### ISSUE TITLE
Can't find the weight file in your link

### ISSUE THREAD

**Issue by chenzhengnan** [MioChiu/TF_CenterNet#2]
Can't find the weight file in your link, Can you resend a link，thanks，

**Comment by MioChiu** [comment]
[pre-trained weight](https://pan.baidu.com/s/1x78snWAsM6kNN94wFmSa6A#list/path=%2F)

**Comment by chenzhengnan** [comment]
Thank you for your reply. Are you Chinese？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"MioChiu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月6日(星期五) 下午5:46
收件人:&nbsp;"MioChiu/TF_CenterNet"<TF_CenterNet@noreply.github.com&gt;;
抄送:&nbsp;"陈正男"<2466692319@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [MioChiu/TF_CenterNet] Can't find the weight file in your link (#2)




pre-trained weight

**Comment by chenzhengnan** [comment]
Is your program configuration requirement CPU or GPU？ @MioChiu

**Comment by MioChiu** [comment]
inference的话CPU GPU都可以 训练还是用GPU吧 = =

**Comment by chenzhengnan** [comment]
有cpu端的开源代码 @MioChiu

**Comment by nrupatunga** [comment]
Can you please upload the weights on Google drive? Unable to download through pan-Baidu link
